[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python run_ui.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Health check configuration
[deploy.healthcheck]
path = "/health"
interval = 30
timeout = 10

# Environment configuration
[env]
PORT = "80"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
TZ = "UTC"
TOKENIZERS_PARALLELISM = "false"
